version: 2

jobs:
  build:
    working_directory: ~/storefront-testing
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Dependencies
          command: yarn global add greenkeeper-lockfile@1
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/node_modules
      - run:
          name: Update Lockfile
          command: greenkeeper-lockfile-update
      - run:
          name: Test
          command: yarn start ci
      - run:
          name: Release
          command: yarn start release || true
      - run:
          name: Upload Lockfile
          command: greenkeeper-lockfile-upload

workflows:
  version: 2

  build_test_release:
    jobs:
      - build:
        context: org-global
        filters:
          branches:
            only: master