version: 2

jobs:
  test:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Test
          command: yarn start ci
  release:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: storefront-testing-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Release
          command: yarn start release || true

workflows:
  version: 2

  build_test_release:
    jobs:
      - test
      - release:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - test
